/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartwaste.gui;

import smartwaste.manager.WasteManager;
import smartwaste.model.WasteBin;
import java.util.Queue;
import java.util.Stack;


/**
 *
 * @author viivihnogueira
 */
public class MainGUI extends javax.swing.JFrame {
    
    private WasteManager manager = new WasteManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /*
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        fillLbl = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        typeCmb = new javax.swing.JComboBox<>();
        fillCmb = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        collectionQueueBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTxt = new javax.swing.JTextArea();
        processBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Waste");
        setBackground(new java.awt.Color(0, 102, 0));

        idLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idLbl.setText("Bin ID:");

        locationLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        locationLbl.setText("Location:");

        typeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        typeLbl.setText("Waste Type:");

        fillLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fillLbl.setText("Fill Level:");

        idTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        locationTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        typeCmb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        typeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recycling", "Organic", "General Waste" }));

        fillCmb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fillCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "25%", "50%", "75%", "Full" }));

        addBtn.setBackground(new java.awt.Color(204, 255, 204));
        addBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        addBtn.setText("Add Bin");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(204, 255, 204));
        updateBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        updateBtn.setText("Update Bin");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(204, 255, 204));
        deleteBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        deleteBtn.setText("Delete Bin");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(204, 255, 204));
        viewBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        viewBtn.setText("View Bins");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        requestBtn.setBackground(new java.awt.Color(255, 255, 204));
        requestBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestBtn.setText("Request Collection");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        collectionQueueBtn.setBackground(new java.awt.Color(255, 255, 204));
        collectionQueueBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        collectionQueueBtn.setText("View Collection Queue");
        collectionQueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionQueueBtnActionPerformed(evt);
            }
        });

        outputTxt.setEditable(false);
        outputTxt.setBackground(new java.awt.Color(204, 204, 255));
        outputTxt.setColumns(20);
        outputTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        outputTxt.setRows(5);
        jScrollPane1.setViewportView(outputTxt);

        processBtn.setBackground(new java.awt.Color(255, 255, 204));
        processBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        processBtn.setText("Process Collection");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        historyBtn.setBackground(new java.awt.Color(204, 204, 255));
        historyBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        historyBtn.setText("View History");
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Monospaced", 3, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 0));
        titleLbl.setText("Smart Waste");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(locationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fillLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fillCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collectionQueueBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(historyBtn)))
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLbl)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLbl)
                            .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLbl)
                            .addComponent(typeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(deleteBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn)
                            .addComponent(viewBtn))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fillCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(requestBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(processBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(collectionQueueBtn)
                        .addGap(18, 18, 18)
                        .addComponent(historyBtn)
                        .addGap(52, 52, 52))))
        );

        titleLbl.getAccessibleContext().setAccessibleName("Smart Waste");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

// not accepting empty fields
if (idTxt.getText().isEmpty() || locationTxt.getText().isEmpty()) {
    outputTxt.setText("");
    outputTxt.append("Please fill in all fields before adding a bin\n");
    return;
}

// accepting users input to add a new bin
       try{
        int binID = Integer.parseInt(idTxt.getText());
        
        // calling method to verify duplicated ids
if (manager.binExists(binID)){
    outputTxt.setText("");
    outputTxt.append("Bin " + binID + " already exists\n");
    return;
}
        
        String location = locationTxt.getText();
        String wasteType = typeCmb.getSelectedItem().toString();
        String fillLevel = fillCmb.getSelectedItem().toString();
        
        //accepting users input to create a bin and displaying the successfuilly added output message
        WasteBin bin = new WasteBin(binID, location, wasteType, fillLevel);
        manager.addBin(bin);
        
        outputTxt.setText("");
        outputTxt.append("Bin "+ binID + " was successfully added\n");
        
        /// cleaning the text fields after bin is added
        
        idTxt.setText("");
        locationTxt.setText("");
        typeCmb.setSelectedIndex(0);
        fillCmb.setSelectedIndex(0);
        
        
    }
       /// if input is invalid 
       catch (NumberFormatException e) {
           outputTxt.setText("");
           outputTxt.append("Please enter a valid number for Bin ID.\n");
       }
    }//GEN-LAST:event_addBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        /// clean the output JTextArea before showing the full bin list
       outputTxt.setText("");
       
       /// display the list of bins added previously in the JTextArea
       for (WasteBin bin : manager.getBins()){
           outputTxt.append(bin.toString() + "\n");
       }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        /// calling the delete method
       try{
           int binID = Integer.parseInt(idTxt.getText());
           boolean removed = manager.deleteBin(binID);
           if (removed){
               outputTxt.setText("");
               outputTxt.append("Bin " + binID + " was deleted successfully\n");
           } else {
               outputTxt.setText("");
               outputTxt.append("Bin " + binID + " not found\n");
           }
       } catch (NumberFormatException e) {
           outputTxt.setText("");
           outputTxt.append("Please enter a valid Bin ID\n");
           
       }
      
         /// cleaning the text fields after bin is added
        
        idTxt.setText("");
        locationTxt.setText("");
        typeCmb.setSelectedIndex(0);
        fillCmb.setSelectedIndex(0);
       
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        /// not accepting empty fields
        if (idTxt.getText().isEmpty() || locationTxt.getText().isEmpty()){
            outputTxt.setText("");
            outputTxt.append("Please fill in all fields before updating a bin\n");
            return;
        }        

// calling update method
        try {
        int binID = Integer.parseInt(idTxt.getText());
        String location = locationTxt.getText();
        String wasteType = typeCmb.getSelectedItem().toString();
        String fillLevel = fillCmb.getSelectedItem().toString();
        
        boolean updated = manager.updateBin(binID, location, wasteType, fillLevel);
        
        if(updated){
            outputTxt.setText("");
            outputTxt.append("Bin " + binID + " updated successfully\n");
        } else {
            outputTxt.setText("");
            outputTxt.append("Bin " + binID + " not found\n");
        }
    } catch (NumberFormatException e) {
        outputTxt.setText("");
        outputTxt.append("Please enter a valid Bin ID\n");
    }
          /// cleaning the text fields after bin is added
        
        idTxt.setText("");
        locationTxt.setText("");
        typeCmb.setSelectedIndex(0);
        fillCmb.setSelectedIndex(0);
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        outputTxt.setText("");
        try{
            int binID = Integer.parseInt(idTxt.getText());
            
            WasteBin selectedBin = null;
            
            /// code to search the bin in the bin list
            for(WasteBin bin : manager.getBins()){
                if(bin.getBinID() == binID){
                    selectedBin = bin;
                    break;
                }
            }
            if (selectedBin != null){
                manager.requestCollection(selectedBin);
                outputTxt.append("Bin " + binID + " added to collection queue\n");
            } else {
                outputTxt.append("Bin " + binID + " not found\n");
            }
        } catch (NumberFormatException e){
            outputTxt.append("Please enter a valid Bin ID\n");
        }
    }//GEN-LAST:event_requestBtnActionPerformed

    private void collectionQueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionQueueBtnActionPerformed
        outputTxt.setText("");
        
        Queue<WasteBin> queue = manager.getCollectionQueue();
        if(queue.isEmpty()){
            outputTxt.append("The collection queue is empty\n");
            return;
        }
        outputTxt.append("Bins waiting for collection:\n");
        outputTxt.append("----------------------------\n");
        
        for(WasteBin bin : queue){
            outputTxt.append("Bin " + bin.getBinID() + " - " + bin.getLocation() + " - " + bin.getWasteType() + " - " + bin.getFillLevel() + "\n");
        }
    }//GEN-LAST:event_collectionQueueBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        outputTxt.setText("");
        
        WasteBin processedBin = manager.processNextCollection();
        
        if(processedBin !=null){
            outputTxt.append("Bin " + processedBin.getBinID() + " has bin collected and added to history\n");
        } else {
            outputTxt.append("No bins in the collection queue\n");
        }
    }//GEN-LAST:event_processBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        outputTxt.setText("");
        
        //gets already processed bins
        Stack<WasteBin> history = manager.getCollectionHistory();
        //gets bins still in the queue
        Queue<WasteBin> queue = manager.getCollectionQueue();
        
        outputTxt.append("=== Processed Bins History ===\n");
        if(history.isEmpty()){
            outputTxt.append("No collection history available\n");
        } else {
        //loop from the top of the Stack to below
        for(int i = history.size() -1; i>=0; i--){
            WasteBin bin = history.get(i);
            outputTxt.append("Bin " + bin.getBinID() + " - " + bin.getLocation() + " - " + bin.getWasteType() + " - " + bin.getFillLevel() + "\n");
        }
    }   
        outputTxt.append("\n === Bins Waiting in Queue ===\n");
        if(queue.isEmpty()){
            outputTxt.append("No bins waiting for collection\n");
        } else {
        
        for(WasteBin bin : queue){
            outputTxt.append("Bin " + bin.getBinID() + " - " + bin.getLocation() + " - " + bin.getWasteType() + " - " + bin.getFillLevel() + "\n");
        }
    }//GEN-LAST:event_historyBtnActionPerformed
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton collectionQueueBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> fillCmb;
    private javax.swing.JLabel fillLbl;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextArea outputTxt;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton requestBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JComboBox<String> typeCmb;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
