/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartwaste.gui;

import smartwaste.manager.WasteManager;
import smartwaste.model.WasteBin;
import java.util.Queue;

/**
 *
 * @author viivihnogueira
 */
public class MainGUI extends javax.swing.JFrame {
    
    private WasteManager manager = new WasteManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /*
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        fillLbl = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        locationTxt = new javax.swing.JTextField();
        typeCmb = new javax.swing.JComboBox<>();
        fillCmb = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        collectionQueueBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLbl.setText("Bin ID:");

        locationLbl.setText("Location:");

        typeLbl.setText("Waste Type:");

        fillLbl.setText("Fill Level:");

        typeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recycling", "Organic", "General Waste" }));

        fillCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empty", "25%", "50%", "75%", "Full" }));

        addBtn.setText("Add Bin");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Bin");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Bin");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View Bins");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        requestBtn.setText("Request Collection");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        collectionQueueBtn.setText("View Collection Queue");
        collectionQueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionQueueBtnActionPerformed(evt);
            }
        });

        outputTxt.setEditable(false);
        outputTxt.setColumns(20);
        outputTxt.setRows(5);
        jScrollPane1.setViewportView(outputTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(fillLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(idLbl)
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationLbl)
                            .addComponent(typeLbl)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addBtn)
                            .addGap(18, 18, 18)
                            .addComponent(updateBtn)
                            .addGap(18, 18, 18)
                            .addComponent(deleteBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeCmb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(locationTxt)
                            .addComponent(fillCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewBtn)
                        .addGap(18, 18, 18)
                        .addComponent(requestBtn)
                        .addGap(18, 18, 18)
                        .addComponent(collectionQueueBtn)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLbl)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl)
                    .addComponent(typeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillLbl)
                    .addComponent(fillCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBtn)
                    .addComponent(requestBtn)
                    .addComponent(collectionQueueBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

// not accepting empty fields
if (idTxt.getText().isEmpty() || locationTxt.getText().isEmpty()) {
    outputTxt.setText("");
    outputTxt.append("Please fill in all fields before adding a bin\n");
    return;
}

// accepting users input to add a new bin
       try{
        int binID = Integer.parseInt(idTxt.getText());
        
        // calling method to verify duplicated ids
if (manager.binExists(binID)){
    outputTxt.setText("");
    outputTxt.append("Bin " + binID + " already exists\n");
    return;
}
        
        String location = locationTxt.getText();
        String wasteType = typeCmb.getSelectedItem().toString();
        String fillLevel = fillCmb.getSelectedItem().toString();
        
        //accepting users input to create a bin and displaying the successfuilly added output message
        WasteBin bin = new WasteBin(binID, location, wasteType, fillLevel);
        manager.addBin(bin);
        
        outputTxt.setText("");
        outputTxt.append("Bin "+ binID + " was successfully added\n");
        
        /// cleaning the text fields after bin is added
        
        idTxt.setText("");
        locationTxt.setText("");
        typeCmb.setSelectedIndex(0);
        fillCmb.setSelectedIndex(0);
        
        
    }
       /// if input is invalid 
       catch (NumberFormatException e) {
           outputTxt.setText("");
           outputTxt.append("Please enter a valid number for Bin ID.\n");
       }
    }//GEN-LAST:event_addBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        /// clean the output JTextArea before showing the full bin list
       outputTxt.setText("");
       
       /// display the list of bins added previously in the JTextArea
       for (WasteBin bin : manager.getBins()){
           outputTxt.append(bin.toString() + "\n");
       }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        /// calling the delete method
       try{
           int binID = Integer.parseInt(idTxt.getText());
           boolean removed = manager.deleteBin(binID);
           if (removed){
               outputTxt.setText("");
               outputTxt.append("Bin " + binID + " was deleted successfully\n");
           } else {
               outputTxt.setText("");
               outputTxt.append("Bin " + binID + " not found\n");
           }
       } catch (NumberFormatException e) {
           outputTxt.setText("");
           outputTxt.append("Please enter a valid Bin ID\n");
           
       }
      
         /// cleaning the text fields after bin is added
        
        idTxt.setText("");
        locationTxt.setText("");
        typeCmb.setSelectedIndex(0);
        fillCmb.setSelectedIndex(0);
       
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        /// not accepting empty fields
        if (idTxt.getText().isEmpty() || locationTxt.getText().isEmpty()){
            outputTxt.setText("");
            outputTxt.append("Please fill in all fields before updating a bin\n");
            return;
        }        

// calling update method
        try {
        int binID = Integer.parseInt(idTxt.getText());
        String location = locationTxt.getText();
        String wasteType = typeCmb.getSelectedItem().toString();
        String fillLevel = fillCmb.getSelectedItem().toString();
        
        boolean updated = manager.updateBin(binID, location, wasteType, fillLevel);
        
        if(updated){
            outputTxt.setText("");
            outputTxt.append("Bin " + binID + " updated successfully\n");
        } else {
            outputTxt.setText("");
            outputTxt.append("Bin " + binID + " not found\n");
        }
    } catch (NumberFormatException e) {
        outputTxt.setText("");
        outputTxt.append("Please enter a valid Bin ID\n");
    }
          /// cleaning the text fields after bin is added
        
        idTxt.setText("");
        locationTxt.setText("");
        typeCmb.setSelectedIndex(0);
        fillCmb.setSelectedIndex(0);
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        outputTxt.setText("");
        try{
            int binID = Integer.parseInt(idTxt.getText());
            
            WasteBin selectedBin = null;
            
            /// code to search the bin in the bin list
            for(WasteBin bin : manager.getBins()){
                if(bin.getBinID() == binID){
                    selectedBin = bin;
                    break;
                }
            }
            if (selectedBin != null){
                manager.requestCollection(selectedBin);
                outputTxt.append("Bin " + binID + " added to collection queue\n");
            } else {
                outputTxt.append("Bin " + binID + " not found\n");
            }
        } catch (NumberFormatException e){
            outputTxt.append("Please enter a valid Bin ID\n");
        }
    }//GEN-LAST:event_requestBtnActionPerformed

    private void collectionQueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionQueueBtnActionPerformed
        outputTxt.setText("");
        
        Queue<WasteBin> queue = manager.getCollectionQueue();
        if(queue.isEmpty()){
            outputTxt.append("The collection queue is empty\n");
            return;
        }
        outputTxt.append("Bins waiting for collection:\n");
        outputTxt.append("----------------------------\n");
        
        for(WasteBin bin : queue){
            outputTxt.append("Bin " + bin.getBinID() + " - " + bin.getLocation() + " - " + bin.getWasteType() + " - " + bin.getFillLevel() + "\n");
        }
    }//GEN-LAST:event_collectionQueueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton collectionQueueBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> fillCmb;
    private javax.swing.JLabel fillLbl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JTextArea outputTxt;
    private javax.swing.JButton requestBtn;
    private javax.swing.JComboBox<String> typeCmb;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
